### ISSUE TITLE
Don't make users wait until ripple effect takes place (MaterialSection)

### ISSUE THREAD

**Issue by egor-n** [neokree/MaterialNavigationDrawer#128]
Right now, when you click on a `MaterialSection` view, it waits until the ripple effect finishes before doing an actual action (as seen [here](https://github.com/neokree/MaterialNavigationDrawer/blob/f8f9460924d87da9dcf4fb06732f67e96901cbc0/MaterialNavigationDrawerModule/src/main/java/it/neokree/materialnavigationdrawer/elements/MaterialSection.java#L266)). I haven't seen any guidelines about this behavior, but that's not how it is done in Google's apps.

In my opinion, the `onClick` should be done right after `ACTION_UP`.

If this issue gets fixed, then #59 and #120 will get fixed automatically. Though #59 will require more work to remove redundant touch canceling code.

**Comment by egor-n** [comment]
Any thoughts on this? This is a deal breaker for me. If you give me the green light on this fix, I'll spend an evening to write up a pull request.

**Comment by neokree** [comment]
Well, with official google apps users wait until the ripple effect is finished, then the drawer will close and the content appear. 
Actually ripple effect is not like official, but I'm working for a better support of it. 

If the <code>onClick</code> will be done right after ACTION_UP the ripple effect is not going to be visible to the user because at the end of the <code>onClick</code> the drawer will be closed.
If you want to remove the ripple effect from your drawer you can add this into your theme:
```xml
<item name="rippleBackport">false</item>
```

**Comment by egor-n** [comment]
Setting `rippleBackport` to `false` disables ripple effect for Lollipop as well. I looked at most of the google apps and didn't find one with the behavior you mentioned. Could you please give me an example?

**Comment by neokree** [comment]
Check the new dev project. I have changed the ripple library and this one works much better than the old.
However, it don't change the fact that the <code>onClick</code> method is called __after__ the ripple effect, like the default lollipop ripple.

**Comment by egor-n** [comment]
Thanks! Just checked out 1.3.1 and the ripple effect is nice, but this issue still stands. I do not understand why `onClick` has to be called after the effect. As I said, I didn't find a single app that does so.

Anyway, Material Ripple library [has a way to turn the daily off](https://github.com/balysv/material-ripple/blob/debf326398fed25ca35903583df77c502be00d54/library/src/main/java/com/balysv/materialripple/MaterialRippleLayout.java#L570). I think you should make the delay optional, too.

**Comment by if12b062** [comment]
This is quite a significant issue for me aswell, as it gives the impression that the appilcation is lagging when the content is displayed only after the ripple is finished and the drawer is nearly closed.

**Comment by neokree** [comment]
I have turned off the delay in this package: [apk without delay](https://github.com/neokree/MaterialNavigationDrawer/raw/master/test-click-before.apk). My opinion is that is not follow material design guidelines and it is never used in google apps app that I have seen. But test for yourself.

**Comment by if12b062** [comment]
Ok this fixes the issue that the drawer does not wait unti the ripple is finished to close itself, but the impression of a lagging application still occurs. The problem here is that the fragments get only replaces after the drawer was closed completely, which is not what the user expects (see several Google apps, e.g. Play Store) when using the application. [There](https://github.com/neokree/MaterialNavigationDrawer/blob/master/MaterialNavigationDrawerModule/src/main/java/it/neokree/materialnavigationdrawer/MaterialNavigationDrawer.java#L542) is the final call to change the fragment, which is far too late.

**Comment by neokree** [comment]
@if12b062 Gmail app loads fragment only when the drawer is completedly closed. 
This is a fact. However, fragments should be loaded **after** the close of the drawer to prevent laggy animations. Check [this](http://stackoverflow.com/questions/17491557/drawerlayouts-item-click-when-is-the-right-time-to-replace-fragment)
