### ISSUE TITLE
setFragment() and setFragmentChild() issues

### ISSUE THREAD

**Issue by rubengees** [neokree/MaterialNavigationDrawer#231]
Hi,
When I call setFragmentChild() there is no back Icon:
![unbenannt](https://cloud.githubusercontent.com/assets/8021265/6577101/acfcae8c-c73b-11e4-95b6-860eef3d980d.png)
This is how I call it:
```java
getMainActivity().setFragmentChild(ExampleFragment.newInstance(exampleParameter), "someTitle");

 private MainActivity getMainActivity(){
        return (MainActivity) getActivity();
  }
```
Moreover I get an error when I call setFragmentChidl() and after that setFragment():
java.lang.IndexOutOfBoundsException
            at java.util.LinkedList.remove(LinkedList.java:660)
            at it.neokree.materialnavigationdrawer.MaterialNavigationDrawer.setFragment(MaterialNavigationDrawer.java:968)
...

**Comment by neokree** [comment]
I don't added the icon because someone doesn't want it. You can download the icon drawable and set it using `setHomeAsUpIndicator();`

remember that this method should be called AFTER the init(), so in your `onStart()` for example.

You can find this in the examples: [MasterChildActivity](https://github.com/neokree/MaterialNavigationDrawer/blob/master/MaterialNavigationDrawer/app/src/main/java/it/neokree/example/functionalities/master_child/MasterChildActivity.java#L29)

**Comment by RubyDerBoss** [comment]
Okay, great. Thank you. Maybe you should include these methods in the wiki so you won't get those questions.
 I think it would be great if you could decide more easily if you want the back button or not. Maybe with a simple boolean parameter showBackButton or whatever in the setFragmentChild method. 

The error appears in a fragment which is fully instantiated. I call these methods after some user input took place.
