### ISSUE TITLE
Light.DarkActionBar cannot have Light action bar feature as Appcompat

### ISSUE THREAD

**Issue by willowcheng** [neokree/MaterialNavigationDrawer#246]
``` xml
    <style name="MainActivityTheme" parent="MaterialNavigationDrawerTheme.Light.DarkActionBar">
        <item name="colorPrimary">@color/theme_default_primary</item>
        <item name="colorPrimaryDark">@color/theme_default_primary_dark</item>
        <item name="colorAccent">@color/theme_accent</item>
        <item name="singleAccount">true</item><!-- Remove the change account button -->
        <item name="rippleBackport">true</item>
        <item name="multipaneSupport">true</item>
    </style>
```

My theme style likes this but popup settings with menu menu button shows dark style. Would like to see the same display feature as `Theme.AppCompat.Light.DarkActionBar`

**Comment by grote** [comment]
This is maybe due to MaterialNavigationDrawerTheme.Light.DarkActionBar using [@style/ThemeOverlay.AppCompat.Dark.ActionBar](https://github.com/neokree/MaterialNavigationDrawer/blob/master/MaterialNavigationDrawerModule/src/main/res/values/themes.xml#L35) as a theme attribute. 

In your case, adding this should help with popups:
```xml
<item name="popupTheme">@style/Base.V21.Theme.AppCompat.Light.Dialog</item>
```
However, I'm having other elements such as buttons also displayed too dark in MaterialNavigationDrawerTheme.Light.DarkActionBar and currently look for a solution.
