### ISSUE TITLE
I want toolbar to be designed by me to add tabs for example

### ISSUE THREAD

**Issue by hisham2007** [neokree/MaterialNavigationDrawer#67]
Thank you very much for this great project and very good documentation.

I just found that Toolbar is included out of the box while I need to design it in XML to add tabs to handle this.

I would do that by setActionBar but I dont want to break your functionality.

Also I think I can getToolbar and modify it by code. But I think it is better to have a way for customizing Action Bar for common scenarios such as tabs.

Thank you,
Hisham

**Comment by h0aX14** [comment]
If you Tabs example is activity than you can simple extend ActionBarActivity and initialize Toolbar by your own layout and style.
If it's an fragment, you can setSectionColor(,,,) method...
If you want to change toolbar when new tab is selected, then.. I simple don't know :laughing:

**Comment by neokree** [comment]
Well, With new Toolbar the tabs should not be included in it. There is a reason if google separates it. 
When I tried to create the materialTabs library for the first time I done this error. Because if you extends Toolbar for inflating your custom tabs you can't do it. Toolbar class supports only to have one view line like the LinearLayout. So I suggest you to create a custom tabs externally extending a Linear or ScrollableView, and use it adding it with the same primaryColor used in your theme at the top of your fragment (attached to the section as target). This new method is more simplier than the old tabs attached to the action bar and takes you the possibility to adds at the top, bottoms, or everywhere you want your tabs.

**Comment by hisham2007** [comment]
Convinced and will close it. Thank you.
