### ISSUE TITLE
Change Text Size

### ISSUE THREAD

**Issue by Mrjerruss** [neokree/MaterialNavigationDrawer#95]
Good afternoon. Is there any way to change the font size in Navigation Drawer? Need larger font.

**Comment by javmarina** [comment]
That would not follow Material Design guidelines...

**Comment by Hondrus** [comment]
And after the last update(1.2.9) text font in section became thinner. Bold font seems better in Cyrillic ):

**Comment by neokree** [comment]
with the last update I will added a little bug with the username, because it don't load the Roboto-Medium font. 
I will update in the next release, but for now you should use an older version if this is a problem. Or you should use the dev version loaded as module and not as maven dependency.

@Mrjerruss If you want to use a larger font on Navigation Drawer Header, you could use the custom header and create your own view. You can also change the size for all font, but in this case you should load the library as a module dependency and modify the layouts.

**Comment by neokree** [comment]
please @Mrjerruss if you think that your problem was resolved, please close the issue
